const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, 'data');
const UPLOAD_DIR = path.join(DATA_DIR, 'uploads');
const DB_FILE = process.env.DATABASE_FILE || path.join(DATA_DIR, 'jan-shield.sqlite');
fs.mkdirSync(UPLOAD_DIR, { recursive: true });
const db = new DatabaseSync(DB_FILE);

const schema = `
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, phone TEXT, profile_image TEXT, address TEXT, language TEXT NOT NULL DEFAULT 'English', role TEXT NOT NULL DEFAULT 'CITIZEN', notification_preferences TEXT NOT NULL DEFAULT '{}', password_hash TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS departments (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, description TEXT, active INTEGER NOT NULL DEFAULT 1, contact TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS complaints (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, location TEXT, ward TEXT, latitude REAL, longitude REAL, landmark TEXT, contact TEXT, priority TEXT NOT NULL DEFAULT 'LOW', priority_score INTEGER NOT NULL DEFAULT 0, priority_reason TEXT, severity TEXT NOT NULL DEFAULT 'LOW', status TEXT NOT NULL DEFAULT 'SUBMITTED', department_id TEXT, is_demo_data INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(department_id) REFERENCES departments(id));
CREATE TABLE IF NOT EXISTS evidence (id TEXT PRIMARY KEY, complaint_id TEXT NOT NULL, file_name TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL, storage_path TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(complaint_id) REFERENCES complaints(id));
CREATE TABLE IF NOT EXISTS ai_analysis (id TEXT PRIMARY KEY, complaint_id TEXT NOT NULL UNIQUE, category TEXT NOT NULL, severity TEXT NOT NULL, summary TEXT NOT NULL, priority_score INTEGER NOT NULL, confidence REAL NOT NULL, affected_area TEXT, duration TEXT, risk_factors TEXT NOT NULL, recommendation TEXT NOT NULL, provider TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(complaint_id) REFERENCES complaints(id));
CREATE TABLE IF NOT EXISTS complaint_relations (id TEXT PRIMARY KEY, complaint_id TEXT NOT NULL, related_complaint_id TEXT NOT NULL, similarity_score REAL NOT NULL, relation_type TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(complaint_id) REFERENCES complaints(id), FOREIGN KEY(related_complaint_id) REFERENCES complaints(id));
CREATE TABLE IF NOT EXISTS complaint_clusters (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, ward TEXT, complaint_count INTEGER NOT NULL DEFAULT 0, similarity REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS systemic_issues (id TEXT PRIMARY KEY, cluster_id TEXT, name TEXT NOT NULL, category TEXT NOT NULL, ward TEXT, complaint_count INTEGER NOT NULL, priority TEXT NOT NULL, confidence REAL NOT NULL, recommended_department_id TEXT, recommended_action TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'OPEN', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(cluster_id) REFERENCES complaint_clusters(id), FOREIGN KEY(recommended_department_id) REFERENCES departments(id));
CREATE TABLE IF NOT EXISTS resolutions (id TEXT PRIMARY KEY, complaint_id TEXT NOT NULL, authority_id TEXT NOT NULL, note TEXT NOT NULL, evidence_id TEXT, status TEXT NOT NULL DEFAULT 'PENDING_VERIFICATION', citizen_comment TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(complaint_id) REFERENCES complaints(id), FOREIGN KEY(authority_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, type TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, actor_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, FOREIGN KEY(actor_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS complaints_user_idx ON complaints(user_id); CREATE INDEX IF NOT EXISTS complaints_status_idx ON complaints(status); CREATE INDEX IF NOT EXISTS complaints_ward_idx ON complaints(ward); CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications(user_id);
`;
db.exec(schema);

const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const hashPassword = (password, salt = crypto.randomBytes(16).toString('hex')) => `${salt}:${crypto.scryptSync(password, salt, 32).toString('hex')}`;
const verifyPassword = (password, stored) => { if (!stored) return false; const [salt, digest] = stored.split(':'); return crypto.timingSafeEqual(Buffer.from(digest, 'hex'), crypto.scryptSync(password, salt, 32)); };
const send = (res, status, body, headers = {}) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', ...headers }); res.end(JSON.stringify(body)); };
const ok = (res, data, message = 'Success', headers) => send(res, 200, { success: true, data, message }, headers);
const fail = (res, status, code, message) => send(res, status, { success: false, error: { code, message } });
const readBody = (req) => new Promise((resolve, reject) => { let raw = ''; req.on('data', (chunk) => { raw += chunk; if (raw.length > 12 * 1024 * 1024) req.destroy(); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); });
const publicUser = (u) => ({ id: u.id, name: u.name, email: u.email, phone: u.phone, profileImage: u.profile_image, address: u.address, language: u.language, role: u.role, notificationPreferences: JSON.parse(u.notification_preferences || '{}'), createdAt: u.created_at, updatedAt: u.updated_at });
const auth = (req) => { const raw = (req.headers.cookie || '').match(/jan_session=([^;]+)/)?.[1]; if (!raw) return null; return db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(crypto.createHash('sha256').update(raw).digest('hex'), now()); };
const requireUser = (req, res, roles = []) => { const user = auth(req); if (!user) { fail(res, 401, 'UNAUTHENTICATED', 'Please sign in to continue.'); return null; } if (roles.length && !roles.includes(user.role)) { fail(res, 403, 'FORBIDDEN', 'You are not authorized for this action.'); return null; } return user; };
const notification = (userId, title, message, type = 'STATUS') => db.prepare('INSERT INTO notifications VALUES (?,?,?,?,?,?,?)').run(id('ntf'), userId, title, message, type, null, now());
const audit = (actorId, action, entityType, entityId, metadata = {}) => db.prepare('INSERT INTO audit_logs VALUES (?,?,?,?,?,?,?)').run(id('log'), actorId, action, entityType, entityId, JSON.stringify(metadata), now());
const department = (category) => db.prepare('SELECT * FROM departments WHERE lower(category)=lower(?) AND active=1 LIMIT 1').get(category);
const scoreComplaint = (input) => { const text = `${input.title} ${input.description}`.toLowerCase(); let score = 15; if (/danger|accident|fire|flood|open wire|unsafe/.test(text)) score += 35; if (/school|hospital|road|water|sewage/.test(text)) score += 15; if (/day|week|month/.test(text)) score += 10; if (input.evidence) score += 10; score = Math.min(100, score); return { score, priority: score >= 80 ? 'CRITICAL' : score >= 60 ? 'HIGH' : score >= 40 ? 'MEDIUM' : 'LOW', reason: 'Calculated from safety risk, duration, location sensitivity, and supporting evidence.' }; };
const analyze = (input) => { const text = `${input.title} ${input.description}`.toLowerCase(); const category = /garbage|kachra|waste|sanitation/.test(text) ? 'Waste Management' : /light|streetlight|bijli/.test(text) ? 'Streetlights' : /water|pani|leak/.test(text) ? 'Water Supply' : /drain|sewage|naali/.test(text) ? 'Drainage' : /pothole|road|traffic/.test(text) ? 'Roads' : input.category || 'Civic Services'; const severity = /danger|fire|flood|accident|unsafe/.test(text) ? 'HIGH' : 'MEDIUM'; const priority = scoreComplaint({ ...input, evidence: Boolean(input.evidence) }); return { category, severity, summary: `Reported ${category.toLowerCase()} issue requiring civic review.`, priorityScore: priority.score, confidence: 0.82, affectedArea: input.ward || input.location || 'Unspecified area', duration: /\d+\s*(day|days|week|weeks)/.exec(text)?.[0] || 'Not provided', riskFactors: severity === 'HIGH' ? ['Public safety risk'] : ['Service disruption'], recommendation: `Route to the ${category} department for inspection and action.`, provider: 'DemoAIProvider', ...priority }; };
function seed() { const t = now(); const existing = db.prepare('SELECT count(*) AS count FROM users').get().count; if (existing) return false; const authority = id('usr'); const citizen = id('usr'); const admin = id('usr'); const insertUser = db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?,?,?,?)'); insertUser.run(authority, 'Asha Rao', 'authority@jan-shield.local', '+91 90000 00001', null, 'Civic Operations Centre', 'English', 'AUTHORITY', '{}', hashPassword('Authority123!'), t, t); insertUser.run(citizen, 'Demo Citizen', 'citizen@jan-shield.local', '+91 90000 00002', null, 'Ward 17', 'English', 'CITIZEN', '{}', hashPassword('Citizen123!'), t, t); insertUser.run(admin, 'System Admin', 'admin@jan-shield.local', '+91 90000 00003', null, 'Civic Operations Centre', 'English', 'ADMIN', '{}', hashPassword('Admin123!'), t, t); const deps = [['Waste Management','Waste Management','Municipal sanitation and collection operations.'],['Roads','Roads','Road repair and infrastructure operations.'],['Water Supply','Water Supply','Water distribution and leak response.'],['Streetlights','Streetlights','Public lighting maintenance.'],['Drainage','Drainage','Stormwater and drainage operations.']]; const depStmt = db.prepare('INSERT INTO departments VALUES (?,?,?,?,?,?,?)'); for (const [name, category, description] of deps) depStmt.run(id('dep'), name, category, description, 1, 'control-room@jan-shield.local', t); const insert = db.prepare('INSERT INTO complaints VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'); for (let i=1;i<=12;i++) { const category = deps[(i-1)%deps.length][1]; const ward = `Ward ${10 + (i%8)}`; const c = { id: `JAN-2026-${String(i).padStart(6,'0')}`, title: `${category} service issue in ${ward}`, description: `Synthetic demonstration report for ${category.toLowerCase()} response tracking.`, category, location: ward, ward, latitude: 28.61 + i/1000, longitude: 77.21 + i/1000, landmark: 'Synthetic demo location', contact: null, priority: i%5===0?'CRITICAL':i%3===0?'HIGH':'MEDIUM', priority_score: i%5===0?86:i%3===0?68:48, priority_reason: 'Synthetic demo record; score illustrates the priority engine.', severity: i%5===0?'HIGH':'MEDIUM', status: i%4===0?'RESOLVED':i%3===0?'IN_PROGRESS':'AI_ANALYZED', department_id: department(category)?.id, is_demo_data: 1, created_at: t, updated_at: t }; insert.run(c.id, citizen, c.title, c.description, c.category, c.location, c.ward, c.latitude, c.longitude, c.landmark, c.contact, c.priority, c.priority_score, c.priority_reason, c.severity, c.status, c.department_id, c.is_demo_data, c.created_at, c.updated_at); if (c.status !== 'SUBMITTED') db.prepare('INSERT INTO ai_analysis VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id('ai'), c.id, c.category, c.severity, `Synthetic analysis for ${c.title}.`, c.priority_score, .9, c.ward, '5 days', JSON.stringify(['Synthetic demo signal']), `Inspect ${c.category.toLowerCase()} service route.`, 'DemoAIProvider', t); } return true; }
seed();

async function route(req, res) { const url = new URL(req.url, 'http://localhost'); const method = req.method; const parts = url.pathname.split('/').filter(Boolean); try {
  if (url.pathname === '/api/auth/register' && method === 'POST') { const b = await readBody(req); if (!b.name || !b.email || !b.password || b.password.length < 8) return fail(res, 400, 'VALIDATION_ERROR', 'Name, email, and a password of 8+ characters are required.'); const user = id('usr'), t = now(); db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(user, String(b.name).trim(), String(b.email).toLowerCase().trim(), b.phone || null, null, b.address || null, b.language || 'English', 'CITIZEN', '{}', hashPassword(b.password), t, t); return loginResponse(res, user); }
  if (url.pathname === '/api/auth/login' && method === 'POST') { const b = await readBody(req); const u = db.prepare('SELECT * FROM users WHERE lower(email)=lower(?)').get(b.email || ''); if (!u || !verifyPassword(b.password || '', u.password_hash)) return fail(res, 401, 'INVALID_CREDENTIALS', 'Email or password is incorrect.'); return loginResponse(res, u.id); }
  if (url.pathname === '/api/auth/logout' && method === 'POST') { const raw = (req.headers.cookie || '').match(/jan_session=([^;]+)/)?.[1]; if (raw) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(crypto.createHash('sha256').update(raw).digest('hex')); return ok(res, null, 'Signed out.', { 'set-cookie': 'jan_session=; Max-Age=0; HttpOnly; SameSite=Lax; Path=/' }); }
  if (url.pathname === '/api/auth/session' && method === 'GET') { const u = auth(req); return ok(res, u ? publicUser(u) : null); }
  const user = requireUser(req, res); if (!user) return;
  if (url.pathname === '/api/profile' && method === 'GET') return ok(res, publicUser(user));
  if (url.pathname === '/api/profile' && method === 'PATCH') { const b = await readBody(req); const email = String(b.email ?? user.email).trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return fail(res,400,'VALIDATION_ERROR','Enter a valid email address.'); const duplicate = db.prepare('SELECT id FROM users WHERE lower(email)=? AND id<>?').get(email,user.id); if (duplicate) return fail(res,409,'EMAIL_IN_USE','That email address is already in use.'); const t=now(); db.prepare('UPDATE users SET name=?,email=?,phone=?,address=?,language=?,notification_preferences=?,updated_at=? WHERE id=?').run(String(b.name ?? user.name).trim(),email,b.phone ?? user.phone,b.address ?? user.address,b.language ?? user.language,JSON.stringify(b.notificationPreferences ?? JSON.parse(user.notification_preferences)),t,user.id); audit(user.id,'PROFILE_UPDATED','User',user.id,{emailChanged:email!==user.email}); return ok(res, publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(user.id)), 'Profile saved.'); }
  if (url.pathname === '/api/complaints' && method === 'GET') { const q=url.searchParams; let sql='SELECT c.*,d.name AS department_name FROM complaints c LEFT JOIN departments d ON d.id=c.department_id WHERE 1=1'; const vals=[]; if(user.role==='CITIZEN'){sql+=' AND c.user_id=?';vals.push(user.id);} for(const [key,col] of [['search','c.title'],['category','c.category'],['priority','c.priority'],['status','c.status'],['ward','c.ward']]) if(q.get(key)){sql+=` AND ${col} LIKE ?`;vals.push(`%${q.get(key)}%`);} sql+=' ORDER BY c.updated_at DESC'; return ok(res, db.prepare(sql).all(...vals).map(complaintView)); }
  if (url.pathname === '/api/complaints' && method === 'POST') { if (user.role !== 'CITIZEN') return fail(res,403,'FORBIDDEN','Only citizen accounts can submit complaints.'); const b=await readBody(req); if(!b.title||!b.description) return fail(res,400,'VALIDATION_ERROR','Title and description are required.'); const recent=db.prepare('SELECT c.*,d.name AS department_name FROM complaints c LEFT JOIN departments d ON d.id=c.department_id WHERE c.user_id=? AND c.title=? AND c.description=? AND c.created_at>? ORDER BY c.created_at DESC LIMIT 1').get(user.id,String(b.title).trim(),String(b.description).trim(),new Date(Date.now()-30000).toISOString()); if(recent)return ok(res,complaintView(recent),'This complaint was already submitted.'); const a=analyze(b), t=now(), year=new Date().getFullYear(), max=db.prepare('SELECT COALESCE(MAX(CAST(substr(id,10) AS INTEGER)),0) AS max FROM complaints WHERE id LIKE ?').get(`JAN-${year}-%`).max, cid=`JAN-${year}-${String(max+1).padStart(6,'0')}`, dep=department(a.category); db.prepare('INSERT INTO complaints VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(cid,user.id,String(b.title).trim(),String(b.description).trim(),a.category,b.location||null,b.ward||null,b.latitude||null,b.longitude||null,b.landmark||null,b.contact||null,a.priority,a.priorityScore,a.reason,a.severity,'AI_ANALYZED',dep?.id||null,0,t,t); db.prepare('INSERT INTO ai_analysis VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id('ai'),cid,a.category,a.severity,a.summary,a.priorityScore,a.confidence,a.affectedArea,a.duration,JSON.stringify(a.riskFactors),a.recommendation,a.provider,t); audit(user.id,'COMPLAINT_CREATED','Complaint',cid,{category:a.category}); notification(user.id,'Complaint received',`${cid} was submitted and analyzed.`,'COMPLAINT'); if(a.priority==='CRITICAL'||a.priority==='HIGH') db.prepare("SELECT id FROM users WHERE role IN ('AUTHORITY','ADMIN')").all().forEach(x=>notification(x.id,'Priority complaint',`${cid} requires attention.`,'ALERT')); return ok(res, complaintView(db.prepare('SELECT c.*,d.name AS department_name FROM complaints c LEFT JOIN departments d ON d.id=c.department_id WHERE c.id=?').get(cid)), 'Complaint submitted.'); }
  if (url.pathname === '/api/evidence' && method === 'POST') { if (user.role !== 'CITIZEN') return fail(res, 403, 'FORBIDDEN', 'Only citizens can attach evidence.'); const b=await readBody(req); const allowed=new Set(['image/jpeg','image/png','image/webp','application/pdf']); if(!b.complaintId||!b.name||!allowed.has(b.type)||!Number.isInteger(b.size)||b.size<1||b.size>10*1024*1024||typeof b.data!=='string') return fail(res,400,'UPLOAD_ERROR','Use a JPG, PNG, WEBP, or PDF file smaller than 10 MB.'); const c=db.prepare('SELECT id FROM complaints WHERE id=? AND user_id=?').get(b.complaintId,user.id); if(!c)return fail(res,404,'NOT_FOUND','Complaint not found.'); const extension=path.extname(String(b.name)).toLowerCase(); if(!['.jpg','.jpeg','.png','.webp','.pdf'].includes(extension))return fail(res,400,'UPLOAD_ERROR','The file extension is not supported.'); const evidenceId=id('evd'), fileName=`${evidenceId}${extension}`, storagePath=path.join(UPLOAD_DIR,fileName); const bytes=Buffer.from(b.data,'base64'); if(bytes.length!==b.size)return fail(res,400,'UPLOAD_ERROR','Evidence size validation failed.'); fs.writeFileSync(storagePath,bytes,{flag:'wx'}); db.prepare('INSERT INTO evidence VALUES (?,?,?,?,?,?,?)').run(evidenceId,c.id,String(b.name).slice(0,180),b.type,b.size,`/data/uploads/${fileName}`,now()); audit(user.id,'EVIDENCE_UPLOADED','Complaint',c.id,{fileName:b.name}); return ok(res,{id:evidenceId,fileName:b.name,url:`/data/uploads/${fileName}`},'Evidence uploaded.'); }
  if (url.pathname === '/api/command-center' && method === 'GET') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Command Center data is restricted to authority users.'); const total=db.prepare('SELECT count(*) AS count FROM complaints').get().count; const active=db.prepare("SELECT count(*) AS count FROM complaints WHERE status NOT IN ('RESOLVED','REJECTED')").get().count; const critical=db.prepare("SELECT count(*) AS count FROM complaints WHERE priority='CRITICAL' AND status NOT IN ('RESOLVED','REJECTED')").get().count; const average=db.prepare("SELECT AVG((julianday(r.updated_at)-julianday(c.created_at))*24) AS hours FROM resolutions r JOIN complaints c ON c.id=r.complaint_id WHERE r.status='RESOLVED'").get().hours; const systemicIssues=db.prepare('SELECT category,ward,count(*) AS complaintCount,avg(priority_score) AS averageScore FROM complaints WHERE ward IS NOT NULL GROUP BY category,ward HAVING count(*)>=2 ORDER BY complaintCount DESC').all().map((row) => ({ id:`${row.category}-${row.ward}`.replace(/\s+/g,'-').toLowerCase(), name:`${row.ward} ${row.category} pattern`, category:row.category, ward:row.ward, complaintCount:row.complaintCount, similarity:Number((row.averageScore/100).toFixed(2)), priority:row.complaintCount>=4?'CRITICAL':'HIGH', confidence:Math.min(.98,.65+row.complaintCount*.05), recommendedAction:`Review repeated ${row.category.toLowerCase()} reports in ${row.ward}.` })); const criticalAlerts=db.prepare("SELECT id,title,category,ward,priority,status,updated_at AS updatedAt FROM complaints WHERE priority='CRITICAL' AND status NOT IN ('RESOLVED','REJECTED') ORDER BY updated_at DESC LIMIT 8").all(); const priorityQueue=db.prepare("SELECT id,title,category,ward,priority,status,updated_at AS updatedAt FROM complaints WHERE status NOT IN ('RESOLVED','REJECTED') ORDER BY CASE priority WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,updated_at DESC LIMIT 10").all(); const departmentPerformance=db.prepare("SELECT d.id,d.name,count(c.id) AS total,sum(CASE WHEN c.status='RESOLVED' THEN 1 ELSE 0 END) AS resolved FROM departments d LEFT JOIN complaints c ON c.department_id=d.id GROUP BY d.id,d.name ORDER BY total DESC,d.name").all().map((row)=>({...row,resolutionRate:row.total?Number((row.resolved/row.total*100).toFixed(1)):null})); const recentActivity=db.prepare('SELECT a.id,a.action,a.entity_type AS entityType,a.entity_id AS entityId,a.created_at AS createdAt,u.name AS actor FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT 10').all(); return ok(res,{metrics:{totalComplaints:total,activeComplaints:active,criticalComplaints:critical,systemicIssues:systemicIssues.length,averageResolutionHours:average===null?null:Number(average.toFixed(1))},criticalAlerts,systemicIssues,priorityQueue,departmentPerformance,recentActivity}); }
  if (parts[0]==='api'&&parts[1]==='complaints'&&parts[2]&&method==='GET') { const c=db.prepare('SELECT c.*,d.name AS department_name FROM complaints c LEFT JOIN departments d ON d.id=c.department_id WHERE c.id=?').get(parts[2]); if(!c|| (user.role==='CITIZEN'&&c.user_id!==user.id)) return fail(res,404,'NOT_FOUND','Complaint not found.'); return ok(res,{...complaintView(c),analysis:db.prepare('SELECT * FROM ai_analysis WHERE complaint_id=?').get(c.id)||null,evidence:db.prepare('SELECT id,file_name AS fileName,mime_type AS mimeType,size FROM evidence WHERE complaint_id=?').all(c.id),related:db.prepare('SELECT r.similarity_score AS similarityScore,r.relation_type AS relationType,c.id,c.title FROM complaint_relations r JOIN complaints c ON c.id=r.related_complaint_id WHERE r.complaint_id=?').all(c.id),resolution:db.prepare('SELECT id,note,status,citizen_comment AS citizenComment,created_at AS createdAt,updated_at AS updatedAt FROM resolutions WHERE complaint_id=? ORDER BY created_at DESC LIMIT 1').get(c.id)||null}); }
  if (parts[0]==='api'&&parts[1]==='complaints'&&parts[2]&&parts[3]==='analyze'&&method==='POST') { const c=db.prepare('SELECT * FROM complaints WHERE id=?').get(parts[2]); if(!c|| (user.role==='CITIZEN'&&c.user_id!==user.id)) return fail(res,404,'NOT_FOUND','Complaint not found.'); const a=analyze(c); db.prepare('INSERT OR REPLACE INTO ai_analysis VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id('ai'),c.id,a.category,a.severity,a.summary,a.priorityScore,a.confidence,a.affectedArea,a.duration,JSON.stringify(a.riskFactors),a.recommendation,a.provider,now()); db.prepare('UPDATE complaints SET category=?,priority=?,priority_score=?,priority_reason=?,severity=?,status=?,updated_at=? WHERE id=?').run(a.category,a.priority,a.priorityScore,a.reason,a.severity,'AI_ANALYZED',now(),c.id); return ok(res,a,'Analysis completed.'); }
  if (parts[0]==='api'&&parts[1]==='complaints'&&parts[2]&&parts[3]==='related'&&method==='GET') { const c=db.prepare('SELECT * FROM complaints WHERE id=?').get(parts[2]); if(!c|| (user.role==='CITIZEN'&&c.user_id!==user.id))return fail(res,404,'NOT_FOUND','Complaint not found.'); const related=db.prepare('SELECT id,title,category,ward,priority,status FROM complaints WHERE id<>? AND category=? AND (ward=? OR ward IS NULL) ORDER BY updated_at DESC LIMIT 10').all(c.id,c.category,c.ward); return ok(res,related.map(x=>({...x,similarityScore:.72,relationType:'CATEGORY_WARD'}))); }
  if (parts[0]==='api'&&parts[1]==='complaints'&&parts[2]&&method==='PATCH') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Only authority users can update complaint workflow.'); const b=await readBody(req); const allowed=['SUBMITTED','AI_ANALYZING','AI_ANALYZED','ASSIGNED','ACTION_INITIATED','IN_PROGRESS','RESOLUTION_PENDING_VERIFICATION','RESOLVED','REOPENED','REJECTED']; if(b.status&&!allowed.includes(b.status)) return fail(res,400,'INVALID_STATUS','Unsupported complaint status.'); const c=db.prepare('SELECT * FROM complaints WHERE id=?').get(parts[2]); if(!c)return fail(res,404,'NOT_FOUND','Complaint not found.'); const dep=b.departmentId||c.department_id; db.prepare('UPDATE complaints SET status=?,department_id=?,updated_at=? WHERE id=?').run(b.status||c.status,dep,now(),c.id); audit(user.id,'COMPLAINT_UPDATED','Complaint',c.id,b); notification(c.user_id,'Complaint updated',`${c.id} is now ${b.status||c.status}.`,'STATUS'); return ok(res,complaintView(db.prepare('SELECT c.*,d.name AS department_name FROM complaints c LEFT JOIN departments d ON d.id=c.department_id WHERE c.id=?').get(c.id)), 'Complaint updated.'); }
  if (parts[0]==='api'&&parts[1]==='complaints'&&parts[2]&&parts[3]==='resolve'&&method==='POST') { if(!['AUTHORITY','ADMIN'].includes(user.role))return fail(res,403,'FORBIDDEN','Only authority users can submit a resolution.'); const b=await readBody(req); if(!String(b.note||'').trim())return fail(res,400,'VALIDATION_ERROR','A resolution note is required.'); const c=db.prepare('SELECT * FROM complaints WHERE id=?').get(parts[2]); if(!c)return fail(res,404,'NOT_FOUND','Complaint not found.'); const t=now(); db.prepare('INSERT INTO resolutions VALUES (?,?,?,?,?,?,?,?,?)').run(id('res'),c.id,user.id,String(b.note).trim(),null,'PENDING_VERIFICATION',null,t,t); db.prepare('UPDATE complaints SET status=?,updated_at=? WHERE id=?').run('RESOLUTION_PENDING_VERIFICATION',t,c.id); audit(user.id,'RESOLUTION_SUBMITTED','Complaint',c.id,{note:String(b.note).trim()}); notification(c.user_id,'Verification required',`${c.id} has a submitted resolution. Please verify the outcome.`,'RESOLUTION'); return ok(res,{complaintId:c.id,status:'RESOLUTION_PENDING_VERIFICATION',note:String(b.note).trim()},'Resolution submitted.'); }
  if (url.pathname === '/api/departments' && method === 'GET') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Department data is restricted to authority users.'); return ok(res,db.prepare('SELECT id,name,category,description,active,contact FROM departments ORDER BY name').all()); }
  if (url.pathname === '/api/systemic-issues' && method === 'GET') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Systemic issue data is restricted to authority users.'); const rows=db.prepare('SELECT category,ward,count(*) AS complaint_count,avg(priority_score) AS similarity FROM complaints WHERE ward IS NOT NULL GROUP BY category,ward HAVING count(*)>=2 ORDER BY complaint_count DESC').all(); return ok(res,rows.map(r=>({id:`${r.category}-${r.ward}`.replace(/\s+/g,'-').toLowerCase(),name:`${r.ward} ${r.category} pattern`,category:r.category,ward:r.ward,complaintCount:r.complaint_count,similarity:Number((r.similarity/100).toFixed(2)),priority:r.complaint_count>=4?'CRITICAL':'HIGH',confidence:Math.min(.98,.65+r.complaint_count*.05),recommendedAction:`Review repeated ${r.category.toLowerCase()} reports in ${r.ward}.`,syntheticEvidence:true}))); }
  if (parts[0]==='api'&&parts[1]==='systemic-issues'&&parts[2]&&method==='GET') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Systemic issue data is restricted to authority users.'); const key=parts[2].replace(/-/g,' '); const rows=db.prepare('SELECT category,ward,count(*) AS complaint_count,avg(priority_score) AS similarity FROM complaints GROUP BY category,ward HAVING lower(category||\'\')||\' \'||lower(ward||\'\') LIKE ?').all(`%${key}%`); if(!rows.length)return fail(res,404,'NOT_FOUND','Systemic issue not found.'); return ok(res,rows[0]); }
  if (parts[0]==='api'&&parts[1]==='systemic-issues'&&parts[2]&&parts[3]==='action'&&method==='POST') { if(!['AUTHORITY','ADMIN'].includes(user.role))return fail(res,403,'FORBIDDEN','Authority authorization is required.'); audit(user.id,'SYSTEMIC_ISSUE_ACTION','SystemicIssue',parts[2]); return ok(res,{id:parts[2],status:'ACTION_INITIATED'},'Systemic issue action recorded.'); }
  if (url.pathname === '/api/notifications' && method === 'GET') return ok(res,db.prepare('SELECT id,title,message,type,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50').all(user.id));
  if (parts[0]==='api'&&parts[1]==='notifications'&&parts[2]&&method==='PATCH') { db.prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(now(),parts[2],user.id); return ok(res,null,'Notification marked read.'); }
  if (url.pathname === '/api/map-data' && method === 'GET') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Map intelligence is restricted to authority users.'); return ok(res,db.prepare('SELECT id,title,category,ward,latitude,longitude,priority,status FROM complaints WHERE latitude IS NOT NULL AND longitude IS NOT NULL').all()); }
  if (url.pathname === '/api/analytics' && method === 'GET') { if(!['AUTHORITY','ADMIN'].includes(user.role)) return fail(res,403,'FORBIDDEN','Analytics are restricted to authority users.'); const total=db.prepare('SELECT count(*) count FROM complaints').get().count; return ok(res,{total,byCategory:db.prepare('SELECT category,count(*) count FROM complaints GROUP BY category').all(),byPriority:db.prepare('SELECT priority,count(*) count FROM complaints GROUP BY priority').all(),byStatus:db.prepare('SELECT status,count(*) count FROM complaints GROUP BY status').all(),systemicIssues:db.prepare('SELECT count(*) count FROM systemic_issues').get().count}); }
  if (parts[0]==='api'&&parts[1]==='complaints'&&parts[2]&&parts[3]==='verify'&&method==='POST') { const c=db.prepare('SELECT * FROM complaints WHERE id=? AND user_id=?').get(parts[2],user.id); if(!c)return fail(res,404,'NOT_FOUND','Complaint not found.'); if(c.status!=='RESOLUTION_PENDING_VERIFICATION')return fail(res,409,'INVALID_STATE','This complaint is not awaiting verification.'); const b=await readBody(req); const status=b.resolved?'RESOLVED':'REOPENED'; const resolution=db.prepare('SELECT id,authority_id FROM resolutions WHERE complaint_id=? ORDER BY created_at DESC LIMIT 1').get(c.id); db.prepare('UPDATE complaints SET status=?,updated_at=? WHERE id=?').run(status,now(),c.id); if(resolution)db.prepare('UPDATE resolutions SET status=?,citizen_comment=?,updated_at=? WHERE id=?').run(status,b.comment||null,now(),resolution.id); audit(user.id,'RESOLUTION_VERIFIED','Complaint',c.id,b); if(status==='REOPENED'&&resolution?.authority_id)notification(resolution.authority_id,'Resolution rejected',`${c.id} was reopened by the citizen.`,'RESOLUTION'); return ok(res,{status},'Your response was recorded.'); }
  return fail(res,404,'NOT_FOUND','The requested resource was not found.');
 } catch (error) { console.error(error); return fail(res,500,'SERVER_ERROR','Something went wrong. Please try again.'); } }
function loginResponse(res,userId){const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES (?,?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),userId,new Date(Date.now()+7*86400000).toISOString(),now());return ok(res,publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(userId)),'Signed in.',{'set-cookie':`jan_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`});}
 function complaintView(c){return {id:c.id,title:c.title,description:c.description,category:c.category,location:c.location,ward:c.ward,latitude:c.latitude,longitude:c.longitude,landmark:c.landmark,contact:c.contact,priority:c.priority,priorityScore:c.priority_score,priorityReason:c.priority_reason,severity:c.severity,status:c.status,department:c.department_name,isDemoData:Boolean(c.is_demo_data),createdAt:c.created_at,updatedAt:c.updated_at};}
function serve(req,res){const file=path.join(ROOT,new URL(req.url,'http://localhost').pathname==='/'?'code.html':new URL(req.url,'http://localhost').pathname);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return fail(res,404,'NOT_FOUND','Page not found.');const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);}
if (process.argv.includes('--migrate')) { console.log('SQLite schema is up to date.'); process.exit(0); }
if (process.argv.includes('--seed')) { console.log(seed()?'Seeded synthetic demo data.':'Seed data already exists.'); process.exit(0); }
const port=Number(process.argv[process.argv.indexOf('--port')+1]||process.env.PORT||3000);http.createServer((req,res)=>req.url.startsWith('/api/')?route(req,res):serve(req,res)).listen(port,'0.0.0.0',()=>console.log(`JAN-SHIELD AI listening on http://0.0.0.0:${port}`));
